name: EvLib-OG
author: NotAlexNoyle
description: A fully LGPLv3 version of EvLib that builds with gradle.
website: https://github.com/true-og/EvLib-OG/
version: '${version}'
api-version: '${apiVersion}'
main: plugin.EvLib
depend: [Utilities-OG, Vault, Essentials]
